/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileSystemView;

/**
 *
 * @author Vulture
 */
public class Browser extends javax.swing.JFrame {

    MainFrame main;
    ArrayList<File> selection;
            
    /**
     * Creates new form Browser
     */
    public Browser(MainFrame main) {
        this.main = main;
        this.selection = new ArrayList<File>();
        initComponents();
        int returnval = browser.showOpenDialog(null); 
        if(returnval == JFileChooser.APPROVE_OPTION) {
            selectFiles(browser.getSelectedFiles());
            this.main.setSelection(selection);
        } else if(returnval == JFileChooser.CANCEL_OPTION) {
            this.dispose();
        }
    }

    private void selectFiles(File files[]) {
        for (File file : files) {
            if (file.isDirectory()) {
                selectFiles(file.listFiles());
            } else if (file.isFile()) {
                this.selection.add(file);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        browser = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);

        browser.setApproveButtonText("Choisir");
        FileSystemView fsv = new ui.FileBrowser();
        browser.setCurrentDirectory(fsv.getParentDirectory(fsv.getParentDirectory(fsv.getParentDirectory(fsv.getHomeDirectory()))));
        browser.setFileSelectionMode(javax.swing.JFileChooser.FILES_AND_DIRECTORIES);
        browser.setMultiSelectionEnabled(true);
        browser.setSelectedFiles(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(browser, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(browser, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser browser;
    // End of variables declaration//GEN-END:variables
}
